language: python
python:
  - "3.6"
  - "3.8"
  - "3.10"
install:
  - pip install -r requirements.txt
script:
  - python -m pytest
notifications:
  email:
    recipients:
      - gramesh4@ncsu.edu
      - hbharat2@ncsu.edu
      - rmante@ncsu.edu

    on_success: never
    on_failure: always
